### PR TITLE
Changes for Embarcadero C++ clang-based compilers, targeting Boost 1.74

### PR DESCRIPTION
**Pull request by eldiener**

### CODE REVIEW

**Comment by eldiener** [comment]
Can this please be merged ?

**Comment by pdimov** [comment]
No, sorry. This is the verbatim source of zlib, used here purely for testing purposes. I don't see what business is it of ours.

**Comment by eldiener** [comment]
The business of ours is that it is incorrect when referring to Embarcadero C++ clang-based compilers. Are you really going to argue that we can not change it because it is "verbatim source" so that a compiler can be used correctly with boost_install ?

**Comment by pdimov** [comment]
boost_install is a b2 module, so patching zlib has no significance to whether it can be used with a particular compiler or not. What problem are you fixing here?

**Comment by eldiener** [comment]
> 
> 
> boost_install is a b2 module, so patching zlib has no significance to whether it can be used with a particular compiler or not. What problem are you fixing here?

Is not the zlib source part of boost_install ? if not why is it part of the source files ?

**Comment by pdimov** [comment]
It's part of the test suite. The tests of boost_install build and install Boost libraries and check whether they are usable from CMake. The zlib source is used to build Iostreams with deflate support on Windows/Appveyor.

Since no Borland compiler is being tested on Appveyor, it doesn't matter whether zlib would compile under it.

**Comment by eldiener** [comment]
> 
> 
> It's part of the test suite. The tests of boost_install build and install Boost libraries and check whether they are usable from CMake. The zlib source is used to build Iostreams with deflate support on Windows/Appveyor.
> 
> Since no Borland compiler is being tested on Appveyor, it doesn't matter whether zlib would compile under it.

But obviously it will matter if we can get Embarcadero C++ clang-based tests running in some sort of CI environment or if we can do regresssion testing for the compiler. I am working on a PR for zlib. But you can close this PR if you wish.

**Comment by eldiener** [comment]
I submitted a PR to zlib for adding Embarcadero C++ clang-based support ( https://github.com/madler/zlib/pull/490 ). The open PRs for zlib are currently at 142 going back to 2013. This is why I think that sometimes Boost needs to fix things for themselves rather than wait for some 3rd party library to do so.

**Pull request closed without merging**
